// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.Metadata.EarthObservation.Ogc.Eop</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.Metadata.EarthObservation.Ogc.Om;
using Terradue.Metadata.EarthObservation.Ogc.Gml321;
using Terradue.Metadata.EarthObservation.Ogc.Ows;
using Terradue.Metadata.EarthObservation.Ogc.Swe;


namespace Terradue.Metadata.EarthObservation.Ogc.Eop {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class EarthObservationType : OM_ObservationType {

        private EarthObservationMetaDataPropertyType metaDataPropertyField;

        private System.Xml.XmlQualifiedName type1Field;

        [System.Xml.Serialization.XmlElementAttribute("metaDataProperty", Order = 0)]
        public EarthObservationMetaDataPropertyType metaDataProperty1 {
            get {
                return this.metaDataPropertyField;
            }
            set {
                this.metaDataPropertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("type", Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class EarthObservationMetaDataPropertyType {

        private EarthObservationMetaDataType earthObservationMetaDataField;

        private bool ownsField;

        public EarthObservationMetaDataPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EarthObservationMetaDataType EarthObservationMetaData {
            get {
                return this.earthObservationMetaDataField;
            }
            set {
                this.earthObservationMetaDataField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservationMetaData", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class EarthObservationMetaDataType {

        private string identifierField;

        private System.DateTime creationDateField;

        private bool creationDateFieldSpecified;

        private System.DateTime modificationDateField;

        private bool modificationDateFieldSpecified;

        private string doiField;

        private string parentIdentifierField;

        private AcquisitionTypeValueType acquisitionTypeField;

        private CodeListType acquisitionSubTypeField;

        private string productTypeField;

        private string statusField;

        private StatusSubTypeValueEnumerationType statusSubTypeField;

        private bool statusSubTypeFieldSpecified;

        private string statusDetailField;

        private DownlinkInformationPropertyType[] downlinkedToField;

        private ArchivingInformationPropertyType[] archivedInField;

        private MeasureType imageQualityDegradationField;

        private MeasureType productQualityDegradationField;

        private string imageQualityDegradationQuotationModeField;

        private string productQualityDegradationQuotationModeField;

        private ImageQualityStatusValueType imageQualityStatusField;

        private bool imageQualityStatusFieldSpecified;

        private ProductQualityStatusValueType productQualityStatusField;

        private bool productQualityStatusFieldSpecified;

        private CodeListType[] imageQualityDegradationTagField;

        private CodeListType[] productQualityDegradationTagField;

        private string imageQualityReportURLField;

        private string productQualityReportURLField;

        private HistogramPropertyType[] histogramsField;

        private EarthObservationPropertyType[] composedOfField;

        private EarthObservationPropertyType[] subsetOfField;

        private EarthObservationPropertyType[] linkedWithField;

        private ProcessingInformationPropertyType[] processingField;

        private string productGroupIdField;

        private SpecificInformationPropertyType[] vendorSpecificField;

        private System.Xml.XmlQualifiedName typeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime modificationDate {
            get {
                return this.modificationDateField;
            }
            set {
                this.modificationDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modificationDateSpecified {
            get {
                return this.modificationDateFieldSpecified;
            }
            set {
                this.modificationDateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string doi {
            get {
                return this.doiField;
            }
            set {
                this.doiField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string parentIdentifier {
            get {
                return this.parentIdentifierField;
            }
            set {
                this.parentIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public AcquisitionTypeValueType acquisitionType {
            get {
                return this.acquisitionTypeField;
            }
            set {
                this.acquisitionTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public CodeListType acquisitionSubType {
            get {
                return this.acquisitionSubTypeField;
            }
            set {
                this.acquisitionSubTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public StatusSubTypeValueEnumerationType statusSubType {
            get {
                return this.statusSubTypeField;
            }
            set {
                this.statusSubTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSubTypeSpecified {
            get {
                return this.statusSubTypeFieldSpecified;
            }
            set {
                this.statusSubTypeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string statusDetail {
            get {
                return this.statusDetailField;
            }
            set {
                this.statusDetailField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("downlinkedTo", Order = 11)]
        public DownlinkInformationPropertyType[] downlinkedTo {
            get {
                return this.downlinkedToField;
            }
            set {
                this.downlinkedToField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("archivedIn", Order = 12)]
        public ArchivingInformationPropertyType[] archivedIn {
            get {
                return this.archivedInField;
            }
            set {
                this.archivedInField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public MeasureType imageQualityDegradation {
            get {
                return this.imageQualityDegradationField;
            }
            set {
                this.imageQualityDegradationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public MeasureType productQualityDegradation {
            get {
                return this.productQualityDegradationField;
            }
            set {
                this.productQualityDegradationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string imageQualityDegradationQuotationMode {
            get {
                return this.imageQualityDegradationQuotationModeField;
            }
            set {
                this.imageQualityDegradationQuotationModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string productQualityDegradationQuotationMode {
            get {
                return this.productQualityDegradationQuotationModeField;
            }
            set {
                this.productQualityDegradationQuotationModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public ImageQualityStatusValueType imageQualityStatus {
            get {
                return this.imageQualityStatusField;
            }
            set {
                this.imageQualityStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageQualityStatusSpecified {
            get {
                return this.imageQualityStatusFieldSpecified;
            }
            set {
                this.imageQualityStatusFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public ProductQualityStatusValueType productQualityStatus {
            get {
                return this.productQualityStatusField;
            }
            set {
                this.productQualityStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productQualityStatusSpecified {
            get {
                return this.productQualityStatusFieldSpecified;
            }
            set {
                this.productQualityStatusFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("imageQualityDegradationTag", Order = 19)]
        public CodeListType[] imageQualityDegradationTag {
            get {
                return this.imageQualityDegradationTagField;
            }
            set {
                this.imageQualityDegradationTagField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("productQualityDegradationTag", Order = 20)]
        public CodeListType[] productQualityDegradationTag {
            get {
                return this.productQualityDegradationTagField;
            }
            set {
                this.productQualityDegradationTagField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 21)]
        public string imageQualityReportURL {
            get {
                return this.imageQualityReportURLField;
            }
            set {
                this.imageQualityReportURLField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", Order = 22)]
        public string productQualityReportURL {
            get {
                return this.productQualityReportURLField;
            }
            set {
                this.productQualityReportURLField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("histograms", Order = 23)]
        public HistogramPropertyType[] histograms {
            get {
                return this.histogramsField;
            }
            set {
                this.histogramsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("composedOf", Order = 24)]
        public EarthObservationPropertyType[] composedOf {
            get {
                return this.composedOfField;
            }
            set {
                this.composedOfField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("subsetOf", Order = 25)]
        public EarthObservationPropertyType[] subsetOf {
            get {
                return this.subsetOfField;
            }
            set {
                this.subsetOfField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("linkedWith", Order = 26)]
        public EarthObservationPropertyType[] linkedWith {
            get {
                return this.linkedWithField;
            }
            set {
                this.linkedWithField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("processing", Order = 27)]
        public ProcessingInformationPropertyType[] processing {
            get {
                return this.processingField;
            }
            set {
                this.processingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public string productGroupId {
            get {
                return this.productGroupIdField;
            }
            set {
                this.productGroupIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("vendorSpecific", Order = 29)]
        public SpecificInformationPropertyType[] vendorSpecific {
            get {
                return this.vendorSpecificField;
            }
            set {
                this.vendorSpecificField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum AcquisitionTypeValueType {

        /// <remarks/>
        OTHER,

        /// <remarks/>
        CALIBRATION,

        /// <remarks/>
        NOMINAL,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("maskMember", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class MaskMemberType : AbstractFeatureMemberType {

        private MaskFeatureType maskFeatureField;

        private string nilReasonField;

        private string remoteSchemaField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MaskFeatureType MaskFeature {
            get {
                return this.maskFeatureField;
            }
            set {
                this.maskFeatureField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema {
            get {
                return this.remoteSchemaField;
            }
            set {
                this.remoteSchemaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("MaskFeature", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class MaskFeatureType : AbstractFeatureType {

        private CodeWithAuthorityType maskTypeField;

        private Terradue.Metadata.EarthObservation.Ogc.Gml311.SurfacePropertyType extentOfField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeWithAuthorityType maskType {
            get {
                return this.maskTypeField;
            }
            set {
                this.maskTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public Terradue.Metadata.EarthObservation.Ogc.Gml311.SurfacePropertyType extentOf {
            get {
                return this.extentOfField;
            }
            set {
                this.extentOfField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Mask", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class MaskType : AbstractFeatureType {

        private MaskMemberType[] maskMemberField;

        [System.Xml.Serialization.XmlElementAttribute("maskMember", Order = 0)]
        public MaskMemberType[] maskMember {
            get {
                return this.maskMemberField;
            }
            set {
                this.maskMemberField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Footprint", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class FootprintType : AbstractFeatureType {

        private MultiSurfacePropertyType multiExtentOfField;

        private PointPropertyType centerOfField;

        private PolygonOrientationValueType orientationField;

        private bool orientationFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MultiSurfacePropertyType multiExtentOf {
            get {
                return this.multiExtentOfField;
            }
            set {
                this.multiExtentOfField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PointPropertyType centerOf {
            get {
                return this.centerOfField;
            }
            set {
                this.centerOfField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public PolygonOrientationValueType orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orientationSpecified {
            get {
                return this.orientationFieldSpecified;
            }
            set {
                this.orientationFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum PolygonOrientationValueType {

        /// <remarks/>
        OTHER,

        /// <remarks/>
        CW,

        /// <remarks/>
        CCW,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservationEquipment", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class EarthObservationEquipmentType : AbstractFeatureType {

        private PlatformPropertyType platformField;

        private InstrumentPropertyType instrumentField;

        private SensorPropertyType sensorField;

        private AcquisitionPropertyType acquisitionParametersField;

        private System.Xml.XmlQualifiedName typeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PlatformPropertyType platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public InstrumentPropertyType instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public SensorPropertyType sensor {
            get {
                return this.sensorField;
            }
            set {
                this.sensorField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public AcquisitionPropertyType acquisitionParameters {
            get {
                return this.acquisitionParametersField;
            }
            set {
                this.acquisitionParametersField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class PlatformPropertyType {

        private PlatformType platformField;

        private bool ownsField;

        public PlatformPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PlatformType Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Platform", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class PlatformType {

        private string shortNameField;

        private string serialIdentifierField;

        private OrbitTypeValueType orbitTypeField;

        private bool orbitTypeFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string serialIdentifier {
            get {
                return this.serialIdentifierField;
            }
            set {
                this.serialIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public OrbitTypeValueType orbitType {
            get {
                return this.orbitTypeField;
            }
            set {
                this.orbitTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orbitTypeSpecified {
            get {
                return this.orbitTypeFieldSpecified;
            }
            set {
                this.orbitTypeFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum OrbitTypeValueType {

        /// <remarks/>
        LEO,

        /// <remarks/>
        GEO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class InstrumentPropertyType {

        private InstrumentType instrumentField;

        private bool ownsField;

        public InstrumentPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public InstrumentType Instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Instrument", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class InstrumentType {

        private string shortNameField;

        private string descriptionField;

        private string instrumentTypeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string instrumentType {
            get {
                return this.instrumentTypeField;
            }
            set {
                this.instrumentTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class SensorPropertyType {

        private SensorType sensorField;

        private bool ownsField;

        public SensorPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SensorType Sensor {
            get {
                return this.sensorField;
            }
            set {
                this.sensorField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Sensor", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class SensorType {

        private string sensorTypeField;

        private CodeListType operationalModeField;

        private MeasureType resolutionField;

        private CodeListType swathIdentifierField;

        private WavelengthInformationPropertyType[] wavelengthInformationField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string sensorType {
            get {
                return this.sensorTypeField;
            }
            set {
                this.sensorTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CodeListType operationalMode {
            get {
                return this.operationalModeField;
            }
            set {
                this.operationalModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MeasureType resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CodeListType swathIdentifier {
            get {
                return this.swathIdentifierField;
            }
            set {
                this.swathIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("wavelengthInformation", Order = 4)]
        public WavelengthInformationPropertyType[] wavelengthInformation {
            get {
                return this.wavelengthInformationField;
            }
            set {
                this.wavelengthInformationField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class WavelengthInformationPropertyType {

        private WavelengthInformationType wavelengthInformationField;

        private bool ownsField;

        public WavelengthInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public WavelengthInformationType WavelengthInformation {
            get {
                return this.wavelengthInformationField;
            }
            set {
                this.wavelengthInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("WavelengthInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class WavelengthInformationType {

        private Terradue.Metadata.EarthObservation.Ogc.Gml311.MeasureListType discreteWavelengthsField;

        private MeasureType endWavelengthField;

        private string spectralRangeField;

        private MeasureType startWavelengthField;

        private MeasureType wavelengthResolutionField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public Terradue.Metadata.EarthObservation.Ogc.Gml311.MeasureListType discreteWavelengths {
            get {
                return this.discreteWavelengthsField;
            }
            set {
                this.discreteWavelengthsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MeasureType endWavelength {
            get {
                return this.endWavelengthField;
            }
            set {
                this.endWavelengthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string spectralRange {
            get {
                return this.spectralRangeField;
            }
            set {
                this.spectralRangeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MeasureType startWavelength {
            get {
                return this.startWavelengthField;
            }
            set {
                this.startWavelengthField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public MeasureType wavelengthResolution {
            get {
                return this.wavelengthResolutionField;
            }
            set {
                this.wavelengthResolutionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class AcquisitionPropertyType {

        private AcquisitionType acquisitionField;

        private bool ownsField;

        public AcquisitionPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AcquisitionType Acquisition {
            get {
                return this.acquisitionField;
            }
            set {
                this.acquisitionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Acquisition", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class AcquisitionType {

        private string orbitNumberField;

        private string lastOrbitNumberField;

        private OrbitDirectionValueType orbitDirectionField;

        private bool orbitDirectionFieldSpecified;

        private CodeWithAuthorityType wrsLongitudeGridField;

        private CodeWithAuthorityType wrsLatitudeGridField;

        private System.DateTime ascendingNodeDateField;

        private bool ascendingNodeDateFieldSpecified;

        private MeasureType ascendingNodeLongitudeField;

        private MeasureType startTimeFromAscendingNodeField;

        private MeasureType completionTimeFromAscendingNodeField;

        private MeasureType orbitDurationField;

        private AngleType illuminationAzimuthAngleField;

        private AngleType illuminationZenithAngleField;

        private AngleType illuminationElevationAngleField;

        private AngleType instrumentAzimuthAngleField;

        private AngleType instrumentZenithAngleField;

        private AngleType instrumentElevationAngleField;

        private AngleType incidenceAngleField;

        private AngleType acrossTrackIncidenceAngleField;

        private AngleType alongTrackIncidenceAngleField;

        private AngleType pitchField;

        private AngleType rollField;

        private AngleType yawField;

        private System.Xml.XmlQualifiedName typeField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string orbitNumber {
            get {
                return this.orbitNumberField;
            }
            set {
                this.orbitNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string lastOrbitNumber {
            get {
                return this.lastOrbitNumberField;
            }
            set {
                this.lastOrbitNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public OrbitDirectionValueType orbitDirection {
            get {
                return this.orbitDirectionField;
            }
            set {
                this.orbitDirectionField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orbitDirectionSpecified {
            get {
                return this.orbitDirectionFieldSpecified;
            }
            set {
                this.orbitDirectionFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CodeWithAuthorityType wrsLongitudeGrid {
            get {
                return this.wrsLongitudeGridField;
            }
            set {
                this.wrsLongitudeGridField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CodeWithAuthorityType wrsLatitudeGrid {
            get {
                return this.wrsLatitudeGridField;
            }
            set {
                this.wrsLatitudeGridField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public System.DateTime ascendingNodeDate {
            get {
                return this.ascendingNodeDateField;
            }
            set {
                this.ascendingNodeDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ascendingNodeDateSpecified {
            get {
                return this.ascendingNodeDateFieldSpecified;
            }
            set {
                this.ascendingNodeDateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public MeasureType ascendingNodeLongitude {
            get {
                return this.ascendingNodeLongitudeField;
            }
            set {
                this.ascendingNodeLongitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public MeasureType startTimeFromAscendingNode {
            get {
                return this.startTimeFromAscendingNodeField;
            }
            set {
                this.startTimeFromAscendingNodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public MeasureType completionTimeFromAscendingNode {
            get {
                return this.completionTimeFromAscendingNodeField;
            }
            set {
                this.completionTimeFromAscendingNodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public MeasureType orbitDuration {
            get {
                return this.orbitDurationField;
            }
            set {
                this.orbitDurationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public AngleType illuminationAzimuthAngle {
            get {
                return this.illuminationAzimuthAngleField;
            }
            set {
                this.illuminationAzimuthAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public AngleType illuminationZenithAngle {
            get {
                return this.illuminationZenithAngleField;
            }
            set {
                this.illuminationZenithAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public AngleType illuminationElevationAngle {
            get {
                return this.illuminationElevationAngleField;
            }
            set {
                this.illuminationElevationAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public AngleType instrumentAzimuthAngle {
            get {
                return this.instrumentAzimuthAngleField;
            }
            set {
                this.instrumentAzimuthAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public AngleType instrumentZenithAngle {
            get {
                return this.instrumentZenithAngleField;
            }
            set {
                this.instrumentZenithAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public AngleType instrumentElevationAngle {
            get {
                return this.instrumentElevationAngleField;
            }
            set {
                this.instrumentElevationAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public AngleType incidenceAngle {
            get {
                return this.incidenceAngleField;
            }
            set {
                this.incidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public AngleType acrossTrackIncidenceAngle {
            get {
                return this.acrossTrackIncidenceAngleField;
            }
            set {
                this.acrossTrackIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public AngleType alongTrackIncidenceAngle {
            get {
                return this.alongTrackIncidenceAngleField;
            }
            set {
                this.alongTrackIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public AngleType pitch {
            get {
                return this.pitchField;
            }
            set {
                this.pitchField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public AngleType roll {
            get {
                return this.rollField;
            }
            set {
                this.rollField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public AngleType yaw {
            get {
                return this.yawField;
            }
            set {
                this.yawField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum OrbitDirectionValueType {

        /// <remarks/>
        ASCENDING,

        /// <remarks/>
        DESCENDING,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservationResult", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class EarthObservationResultType : AbstractFeatureType {

        private BrowseInformationPropertyType[] browseField;

        private ProductInformationPropertyType[] productField;

        private MaskInformationPropertyType[] maskField;

        private ParameterInformationPropertyType parameterField;

        private Terradue.Metadata.EarthObservation.Ogc.Gml321.ReferenceType[] coverageField;

        private System.Xml.XmlQualifiedName typeField;

        [System.Xml.Serialization.XmlElementAttribute("browse", Order = 0)]
        public BrowseInformationPropertyType[] browse {
            get {
                return this.browseField;
            }
            set {
                this.browseField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("product", Order = 1)]
        public ProductInformationPropertyType[] product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("mask", Order = 2)]
        public MaskInformationPropertyType[] mask {
            get {
                return this.maskField;
            }
            set {
                this.maskField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ParameterInformationPropertyType parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("coverage", Order = 4)]
        public Terradue.Metadata.EarthObservation.Ogc.Gml321.ReferenceType[] coverage {
            get {
                return this.coverageField;
            }
            set {
                this.coverageField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class BrowseInformationPropertyType {

        private BrowseInformationType browseInformationField;

        private bool ownsField;

        public BrowseInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public BrowseInformationType BrowseInformation {
            get {
                return this.browseInformationField;
            }
            set {
                this.browseInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("BrowseInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class BrowseInformationType {

        private string typeField;

        private CodeListType subTypeField;

        private CodeWithAuthorityType referenceSystemIdentifierField;

        private BrowseInformationTypeFileName fileNameField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CodeListType subType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CodeWithAuthorityType referenceSystemIdentifier {
            get {
                return this.referenceSystemIdentifierField;
            }
            set {
                this.referenceSystemIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public BrowseInformationTypeFileName fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class BrowseInformationTypeFileName {

        private ServiceReferenceType serviceReferenceField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/2.0", Order = 0)]
        public ServiceReferenceType ServiceReference {
            get {
                return this.serviceReferenceField;
            }
            set {
                this.serviceReferenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class ProductInformationPropertyType {

        private ProductInformationType productInformationField;

        private bool ownsField;

        public ProductInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ProductInformationType ProductInformation {
            get {
                return this.productInformationField;
            }
            set {
                this.productInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("ProductInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class ProductInformationType {

        private CodeWithAuthorityType referenceSystemIdentifierField;

        private ProductInformationTypeFileName fileNameField;

        private string versionField;

        private Terradue.Metadata.EarthObservation.Ogc.Gml311.MeasureListType sizeField;

        private CodeListType timelinessField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeWithAuthorityType referenceSystemIdentifier {
            get {
                return this.referenceSystemIdentifierField;
            }
            set {
                this.referenceSystemIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ProductInformationTypeFileName fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public Terradue.Metadata.EarthObservation.Ogc.Gml311.MeasureListType size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CodeListType timeliness {
            get {
                return this.timelinessField;
            }
            set {
                this.timelinessField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class ProductInformationTypeFileName {

        private ServiceReferenceType serviceReferenceField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/2.0", Order = 0)]
        public ServiceReferenceType ServiceReference {
            get {
                return this.serviceReferenceField;
            }
            set {
                this.serviceReferenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class MaskInformationPropertyType {

        private MaskInformationType maskInformationField;

        private bool ownsField;

        public MaskInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MaskInformationType MaskInformation {
            get {
                return this.maskInformationField;
            }
            set {
                this.maskInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("MaskInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class MaskInformationType {

        private string typeField;

        private string subTypeField;

        private string formatField;

        private CodeWithAuthorityType referenceSystemIdentifierField;

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string subType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CodeWithAuthorityType referenceSystemIdentifier {
            get {
                return this.referenceSystemIdentifierField;
            }
            set {
                this.referenceSystemIdentifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("fileName", typeof(MaskInformationTypeFileName), Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute("multiExtentOf", typeof(MultiSurfacePropertyType), Order = 4)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class MaskInformationTypeFileName {

        private ServiceReferenceType serviceReferenceField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/ows/2.0", Order = 0)]
        public ServiceReferenceType ServiceReference {
            get {
                return this.serviceReferenceField;
            }
            set {
                this.serviceReferenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class ParameterInformationPropertyType {

        private ParameterInformationType parameterInformationField;

        private bool ownsField;

        public ParameterInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ParameterInformationType ParameterInformation {
            get {
                return this.parameterInformationField;
            }
            set {
                this.parameterInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("ParameterInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class ParameterInformationType {

        private UnitOfMeasureType[] unitOfMeasureField;

        private PhenomenonPropertyType phenomenonField;

        [System.Xml.Serialization.XmlElementAttribute("unitOfMeasure", Order = 0)]
        public UnitOfMeasureType[] unitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PhenomenonPropertyType phenomenon {
            get {
                return this.phenomenonField;
            }
            set {
                this.phenomenonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class FootprintPropertyType {

        private FootprintType footprintField;

        private string nilReasonField;

        private string remoteSchemaField;

        private bool ownsField;

        public FootprintPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public FootprintType Footprint {
            get {
                return this.footprintField;
            }
            set {
                this.footprintField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema {
            get {
                return this.remoteSchemaField;
            }
            set {
                this.remoteSchemaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class EarthObservationEquipmentPropertyType {

        private EarthObservationEquipmentType earthObservationEquipmentField;

        private string nilReasonField;

        private string remoteSchemaField;

        private bool ownsField;

        public EarthObservationEquipmentPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EarthObservationEquipmentType EarthObservationEquipment {
            get {
                return this.earthObservationEquipmentField;
            }
            set {
                this.earthObservationEquipmentField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema {
            get {
                return this.remoteSchemaField;
            }
            set {
                this.remoteSchemaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class EarthObservationResultPropertyType {

        private EarthObservationResultType earthObservationResultField;

        private string nilReasonField;

        private string remoteSchemaField;

        private bool ownsField;

        public EarthObservationResultPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EarthObservationResultType EarthObservationResult {
            get {
                return this.earthObservationResultField;
            }
            set {
                this.earthObservationResultField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema {
            get {
                return this.remoteSchemaField;
            }
            set {
                this.remoteSchemaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("SpecificInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class SpecificInformationType {

        private string localAttributeField;

        private string localValueField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string localAttribute {
            get {
                return this.localAttributeField;
            }
            set {
                this.localAttributeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string localValue {
            get {
                return this.localValueField;
            }
            set {
                this.localValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class SpecificInformationPropertyType {

        private SpecificInformationType specificInformationField;

        private bool ownsField;

        public SpecificInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SpecificInformationType SpecificInformation {
            get {
                return this.specificInformationField;
            }
            set {
                this.specificInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("ProcessingInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class ProcessingInformationType {

        private CodeListType processingCenterField;

        private System.DateTime processingDateField;

        private bool processingDateFieldSpecified;

        private string compositeTypeField;

        private string methodField;

        private string methodVersionField;

        private string processorNameField;

        private string processorVersionField;

        private string processingLevelField;

        private string nativeProductFormatField;

        private string[] auxiliaryDataSetFileNameField;

        private CodeListType processingModeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeListType processingCenter {
            get {
                return this.processingCenterField;
            }
            set {
                this.processingCenterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime processingDate {
            get {
                return this.processingDateField;
            }
            set {
                this.processingDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processingDateSpecified {
            get {
                return this.processingDateFieldSpecified;
            }
            set {
                this.processingDateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration", Order = 2)]
        public string compositeType {
            get {
                return this.compositeTypeField;
            }
            set {
                this.compositeTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string methodVersion {
            get {
                return this.methodVersionField;
            }
            set {
                this.methodVersionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string processorName {
            get {
                return this.processorNameField;
            }
            set {
                this.processorNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string processorVersion {
            get {
                return this.processorVersionField;
            }
            set {
                this.processorVersionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string processingLevel {
            get {
                return this.processingLevelField;
            }
            set {
                this.processingLevelField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string nativeProductFormat {
            get {
                return this.nativeProductFormatField;
            }
            set {
                this.nativeProductFormatField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("auxiliaryDataSetFileName", Order = 9)]
        public string[] auxiliaryDataSetFileName {
            get {
                return this.auxiliaryDataSetFileNameField;
            }
            set {
                this.auxiliaryDataSetFileNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public CodeListType processingMode {
            get {
                return this.processingModeField;
            }
            set {
                this.processingModeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class ProcessingInformationPropertyType {

        private ProcessingInformationType processingInformationField;

        private bool ownsField;

        public ProcessingInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ProcessingInformationType ProcessingInformation {
            get {
                return this.processingInformationField;
            }
            set {
                this.processingInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Histogram", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class HistogramType {

        private string bandIdField;

        private string minField;

        private string maxField;

        private decimal meanField;

        private bool meanFieldSpecified;

        private decimal stdDeviationField;

        private bool stdDeviationFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string bandId {
            get {
                return this.bandIdField;
            }
            set {
                this.bandIdField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public decimal mean {
            get {
                return this.meanField;
            }
            set {
                this.meanField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meanSpecified {
            get {
                return this.meanFieldSpecified;
            }
            set {
                this.meanFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal stdDeviation {
            get {
                return this.stdDeviationField;
            }
            set {
                this.stdDeviationField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stdDeviationSpecified {
            get {
                return this.stdDeviationFieldSpecified;
            }
            set {
                this.stdDeviationFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class HistogramPropertyType {

        private HistogramType histogramField;

        private bool ownsField;

        public HistogramPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public HistogramType Histogram {
            get {
                return this.histogramField;
            }
            set {
                this.histogramField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("ArchivingInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class ArchivingInformationType {

        private CodeListType archivingCenterField;

        private System.DateTime archivingDateField;

        private Terradue.Metadata.EarthObservation.Ogc.Gml321.CodeType archivingIdentifierField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeListType archivingCenter {
            get {
                return this.archivingCenterField;
            }
            set {
                this.archivingCenterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime archivingDate {
            get {
                return this.archivingDateField;
            }
            set {
                this.archivingDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public Terradue.Metadata.EarthObservation.Ogc.Gml321.CodeType archivingIdentifier {
            get {
                return this.archivingIdentifierField;
            }
            set {
                this.archivingIdentifierField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class ArchivingInformationPropertyType {

        private ArchivingInformationType archivingInformationField;

        private bool ownsField;

        public ArchivingInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ArchivingInformationType ArchivingInformation {
            get {
                return this.archivingInformationField;
            }
            set {
                this.archivingInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("DownlinkInformation", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = false)]
    public partial class DownlinkInformationType {

        private CodeListType acquisitionStationField;

        private System.DateTime acquisitionDateField;

        private bool acquisitionDateFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeListType acquisitionStation {
            get {
                return this.acquisitionStationField;
            }
            set {
                this.acquisitionStationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime acquisitionDate {
            get {
                return this.acquisitionDateField;
            }
            set {
                this.acquisitionDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acquisitionDateSpecified {
            get {
                return this.acquisitionDateFieldSpecified;
            }
            set {
                this.acquisitionDateFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class DownlinkInformationPropertyType {

        private DownlinkInformationType downlinkInformationField;

        private bool ownsField;

        public DownlinkInformationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public DownlinkInformationType DownlinkInformation {
            get {
                return this.downlinkInformationField;
            }
            set {
                this.downlinkInformationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class EarthObservationPropertyType {

        private EarthObservationType earthObservationField;

        private string nilReasonField;

        private string remoteSchemaField;

        private bool ownsField;

        public EarthObservationPropertyType() {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public EarthObservationType EarthObservation {
            get {
                return this.earthObservationField;
            }
            set {
                this.earthObservationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema {
            get {
                return this.remoteSchemaField;
            }
            set {
                this.remoteSchemaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns {
            get {
                return this.ownsField;
            }
            set {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum StatusSubTypeValueEnumerationType {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ON-LINE")]
        ONLINE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OFF-LINE")]
        OFFLINE,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum ImageQualityStatusValueType {

        /// <remarks/>
        NOMINAL,

        /// <remarks/>
        DEGRADED,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public enum ProductQualityStatusValueType {

        /// <remarks/>
        DEGRADED,

        /// <remarks/>
        NOMINAL,
    }
}
