// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.Metadata.EarthObservation.Ogc.Sar</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.Metadata.EarthObservation.Ogc.Om;
using Terradue.Metadata.EarthObservation.Ogc.Eop;
using Terradue.Metadata.EarthObservation.Ogc.Gml321;


namespace Terradue.Metadata.EarthObservation.Ogc.Sar
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "EarthObservationType", Namespace = "http://www.opengis.net/sar/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservation", Namespace = "http://www.opengis.net/sar/2.1", IsNullable = false)]
    public partial class SarEarthObservationType : EarthObservationType
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SarEarthObservationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class EarthObservationType : OM_ObservationType
    {

        private EarthObservationMetaDataPropertyType metaDataPropertyField;

        private System.Xml.XmlQualifiedName type1Field;

        [System.Xml.Serialization.XmlElementAttribute("metaDataProperty", Order = 0)]
        public EarthObservationMetaDataPropertyType metaDataProperty1
        {
            get
            {
                return this.metaDataPropertyField;
            }
            set
            {
                this.metaDataPropertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("type", Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type1
        {
            get
            {
                return this.type1Field;
            }
            set
            {
                this.type1Field = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class AcquisitionPropertyType
    {

        private AcquisitionType acquisitionField;

        private bool ownsField;

        public AcquisitionPropertyType()
        {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AcquisitionType Acquisition
        {
            get
            {
                return this.acquisitionField;
            }
            set
            {
                this.acquisitionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns
        {
            get
            {
                return this.ownsField;
            }
            set
            {
                this.ownsField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AcquisitionType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class AcquisitionType
    {

        private string orbitNumberField;

        private string lastOrbitNumberField;

        private OrbitDirectionValueType orbitDirectionField;

        private bool orbitDirectionFieldSpecified;

        private CodeWithAuthorityType wrsLongitudeGridField;

        private CodeWithAuthorityType wrsLatitudeGridField;

        private System.DateTime ascendingNodeDateField;

        private bool ascendingNodeDateFieldSpecified;

        private MeasureType ascendingNodeLongitudeField;

        private MeasureType startTimeFromAscendingNodeField;

        private MeasureType completionTimeFromAscendingNodeField;

        private MeasureType orbitDurationField;

        private AngleType illuminationAzimuthAngleField;

        private AngleType illuminationZenithAngleField;

        private AngleType illuminationElevationAngleField;

        private AngleType instrumentAzimuthAngleField;

        private AngleType instrumentZenithAngleField;

        private AngleType instrumentElevationAngleField;

        private AngleType incidenceAngleField;

        private AngleType acrossTrackIncidenceAngleField;

        private AngleType alongTrackIncidenceAngleField;

        private AngleType pitchField;

        private AngleType rollField;

        private AngleType yawField;

        private System.Xml.XmlQualifiedName typeField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string orbitNumber
        {
            get
            {
                return this.orbitNumberField;
            }
            set
            {
                this.orbitNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string lastOrbitNumber
        {
            get
            {
                return this.lastOrbitNumberField;
            }
            set
            {
                this.lastOrbitNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public OrbitDirectionValueType orbitDirection
        {
            get
            {
                return this.orbitDirectionField;
            }
            set
            {
                this.orbitDirectionField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orbitDirectionSpecified
        {
            get
            {
                return this.orbitDirectionFieldSpecified;
            }
            set
            {
                this.orbitDirectionFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CodeWithAuthorityType wrsLongitudeGrid
        {
            get
            {
                return this.wrsLongitudeGridField;
            }
            set
            {
                this.wrsLongitudeGridField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CodeWithAuthorityType wrsLatitudeGrid
        {
            get
            {
                return this.wrsLatitudeGridField;
            }
            set
            {
                this.wrsLatitudeGridField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public System.DateTime ascendingNodeDate
        {
            get
            {
                return this.ascendingNodeDateField;
            }
            set
            {
                this.ascendingNodeDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ascendingNodeDateSpecified
        {
            get
            {
                return this.ascendingNodeDateFieldSpecified;
            }
            set
            {
                this.ascendingNodeDateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public MeasureType ascendingNodeLongitude
        {
            get
            {
                return this.ascendingNodeLongitudeField;
            }
            set
            {
                this.ascendingNodeLongitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public MeasureType startTimeFromAscendingNode
        {
            get
            {
                return this.startTimeFromAscendingNodeField;
            }
            set
            {
                this.startTimeFromAscendingNodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public MeasureType completionTimeFromAscendingNode
        {
            get
            {
                return this.completionTimeFromAscendingNodeField;
            }
            set
            {
                this.completionTimeFromAscendingNodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public MeasureType orbitDuration
        {
            get
            {
                return this.orbitDurationField;
            }
            set
            {
                this.orbitDurationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public AngleType illuminationAzimuthAngle
        {
            get
            {
                return this.illuminationAzimuthAngleField;
            }
            set
            {
                this.illuminationAzimuthAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public AngleType illuminationZenithAngle
        {
            get
            {
                return this.illuminationZenithAngleField;
            }
            set
            {
                this.illuminationZenithAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public AngleType illuminationElevationAngle
        {
            get
            {
                return this.illuminationElevationAngleField;
            }
            set
            {
                this.illuminationElevationAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public AngleType instrumentAzimuthAngle
        {
            get
            {
                return this.instrumentAzimuthAngleField;
            }
            set
            {
                this.instrumentAzimuthAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public AngleType instrumentZenithAngle
        {
            get
            {
                return this.instrumentZenithAngleField;
            }
            set
            {
                this.instrumentZenithAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public AngleType instrumentElevationAngle
        {
            get
            {
                return this.instrumentElevationAngleField;
            }
            set
            {
                this.instrumentElevationAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public AngleType incidenceAngle
        {
            get
            {
                return this.incidenceAngleField;
            }
            set
            {
                this.incidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public AngleType acrossTrackIncidenceAngle
        {
            get
            {
                return this.acrossTrackIncidenceAngleField;
            }
            set
            {
                this.acrossTrackIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public AngleType alongTrackIncidenceAngle
        {
            get
            {
                return this.alongTrackIncidenceAngleField;
            }
            set
            {
                this.alongTrackIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public AngleType pitch
        {
            get
            {
                return this.pitchField;
            }
            set
            {
                this.pitchField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public AngleType roll
        {
            get
            {
                return this.rollField;
            }
            set
            {
                this.rollField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public AngleType yaw
        {
            get
            {
                return this.yawField;
            }
            set
            {
                this.yawField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.Xml.XmlQualifiedName type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AcquisitionType", Namespace = "http://www.opengis.net/sar/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Acquisition", Namespace = "http://www.opengis.net/sar/2.1", IsNullable = false)]
    public partial class AcquisitionType1 : AcquisitionType
    {

        private string polarisationModeField;

        private string polarisationChannelsField;

        private string antennaLookDirectionField;

        private AngleType minimumIncidenceAngleField;

        private AngleType maximumIncidenceAngleField;

        private AngleType incidenceAngleVariationField;

        private MeasureType dopplerFrequencyField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string polarisationMode
        {
            get
            {
                return this.polarisationModeField;
            }
            set
            {
                this.polarisationModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string polarisationChannels
        {
            get
            {
                return this.polarisationChannelsField;
            }
            set
            {
                this.polarisationChannelsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string antennaLookDirection
        {
            get
            {
                return this.antennaLookDirectionField;
            }
            set
            {
                this.antennaLookDirectionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public AngleType minimumIncidenceAngle
        {
            get
            {
                return this.minimumIncidenceAngleField;
            }
            set
            {
                this.minimumIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public AngleType maximumIncidenceAngle
        {
            get
            {
                return this.maximumIncidenceAngleField;
            }
            set
            {
                this.maximumIncidenceAngleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public AngleType incidenceAngleVariation
        {
            get
            {
                return this.incidenceAngleVariationField;
            }
            set
            {
                this.incidenceAngleVariationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public MeasureType dopplerFrequency
        {
            get
            {
                return this.dopplerFrequencyField;
            }
            set
            {
                this.dopplerFrequencyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AcquisitionPropertyType", Namespace = "http://www.opengis.net/sar/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("AcquisitionPropertyType", Namespace = "http://www.opengis.net/sar/2.1", IsNullable = true)]
    public partial class AcquisitionPropertyType1
    {

        private AcquisitionType1 acquisitionField;

        private bool ownsField;

        public AcquisitionPropertyType1()
        {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AcquisitionType1 Acquisition
        {
            get
            {
                return this.acquisitionField;
            }
            set
            {
                this.acquisitionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns
        {
            get
            {
                return this.ownsField;
            }
            set
            {
                this.ownsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/sar/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/sar/2.1", IsNullable = true)]
    public partial class EarthObservationPropertyType
    {

        private SarEarthObservationType earthObservationField;

        private string nilReasonField;

        private string remoteSchemaField;

        private bool ownsField;

        public EarthObservationPropertyType()
        {
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SarEarthObservationType EarthObservation
        {
            get
            {
                return this.earthObservationField;
            }
            set
            {
                this.earthObservationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason
        {
            get
            {
                return this.nilReasonField;
            }
            set
            {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.opengis.net/gml/3.2", DataType = "anyURI")]
        public string remoteSchema
        {
            get
            {
                return this.remoteSchemaField;
            }
            set
            {
                this.remoteSchemaField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns
        {
            get
            {
                return this.ownsField;
            }
            set
            {
                this.ownsField = value;
            }
        }
    }
}
