// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>ClassLibrary5</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.GeoJson.Gml;
using Terradue.Metadata.EarthObservation.Ogc.Eop;
using Terradue.Metadata.EarthObservation.Ogc.Om;


namespace Terradue.Metadata.EarthObservation.Ogc.Lmb
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "EarthObservationType", Namespace = "http://www.opengis.net/sar/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservation", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbEarthObservationType : EarthObservationType
    {

        private OM_ProcessPropertyType procedureField;

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/om/2.0", Type=typeof(LmbEarthObservationEquipmentPropertyType))]
        public override OM_ProcessPropertyType procedure
        {
            get
            {
                return this.procedureField;
            }
            set
            {
                this.procedureField = value;
            }
        }

        [XmlIgnore]
        public LmbEarthObservationEquipmentPropertyType SarEarthObservationEquipment
        {
            get
            {
                return (LmbEarthObservationEquipmentPropertyType)this.procedureField;
            }
            set
            {
                this.procedureField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.opengis.net/om/2.0", Type=typeof(LmbFootprintPropertyType), IsNullable = true)]
        public LmbFootprintPropertyType LmbFeatureOfInterest
        {
            get
            {
                return (LmbFootprintPropertyType)this.featureOfInterest;
            }
            set
            {
                this.featureOfInterest = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class LmbEarthObservationEquipmentPropertyType : EarthObservationEquipmentPropertyType
    {
        private EarthObservationEquipmentType earthObservationEquipmentField;

        [System.Xml.Serialization.XmlElementAttribute(Type = typeof(LmbEarthObservationEquipmentType))]
        public override EarthObservationEquipmentType EarthObservationEquipment
        {
            get
            {
                return this.earthObservationEquipmentField;
            }
            set
            {
                this.earthObservationEquipmentField = value;
            }
        }

        [XmlIgnore]
        public LmbEarthObservationEquipmentType LmbEarthObservationEquipment
        {
            get
            {
                return (LmbEarthObservationEquipmentType)this.earthObservationEquipmentField;
            }
            set
            {
                this.earthObservationEquipmentField = value;
            }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "EarthObservationEquipmentType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservationEquipment", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbEarthObservationEquipmentType : EarthObservationEquipmentType
    {

        private AcquisitionPropertyType acquisitionParameters1Field;

        private SensorPropertyType sensor1Field;

        /// <summary>
        /// EarthObservationEquipmentType1 class constructor
        /// </summary>
        public LmbEarthObservationEquipmentType()
        {
            this.sensor1Field = new SensorPropertyType();
            this.acquisitionParameters1Field = new AcquisitionPropertyType();
        }

        [System.Xml.Serialization.XmlElementAttribute("acquisitionParameters", Order = 0)]
        public AcquisitionPropertyType acquisitionParameters1
        {
            get
            {
                return this.acquisitionParameters1Field;
            }
            set
            {
                this.acquisitionParameters1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("sensor", Order = 1)]
        public SensorPropertyType sensor1
        {
            get
            {
                return this.sensor1Field;
            }
            set
            {
                this.sensor1Field = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class AcquisitionPropertyType
    {

        private AcquisitionType acquisitionField;

        private bool ownsField;

        public AcquisitionPropertyType()
        {
            this.acquisitionField = new AcquisitionType();
            this.ownsField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public AcquisitionType Acquisition
        {
            get
            {
                return this.acquisitionField;
            }
            set
            {
                this.acquisitionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool owns
        {
            get
            {
                return this.ownsField;
            }
            set
            {
                this.ownsField = value;
            }
        }
    }
        

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "FootprintType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Footprint", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbFootprintType : FootprintType
    {

        private MeasureType maximumAltitudeField;

        private MeasureType minimumAltitudeField;

        private MultiCurvePropertyType nominalTrackField;

        private MultiPointPropertyType occultationPointsField;

        /// <summary>
        /// FootprintType1 class constructor
        /// </summary>
        public LmbFootprintType()
        {
            this.occultationPointsField = new MultiPointPropertyType();
            this.nominalTrackField = new MultiCurvePropertyType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MeasureType maximumAltitude
        {
            get
            {
                return this.maximumAltitudeField;
            }
            set
            {
                this.maximumAltitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MeasureType minimumAltitude
        {
            get
            {
                return this.minimumAltitudeField;
            }
            set
            {
                this.minimumAltitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MultiCurvePropertyType nominalTrack
        {
            get
            {
                return this.nominalTrackField;
            }
            set
            {
                this.nominalTrackField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MultiPointPropertyType occultationPoints
        {
            get
            {
                return this.occultationPointsField;
            }
            set
            {
                this.occultationPointsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SensorType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Sensor", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbSensorType : SensorType
    {

        private MeasurementTypeValueType measurementTypeField;

        private bool measurementTypeFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MeasurementTypeValueType measurementType
        {
            get
            {
                return this.measurementTypeField;
            }
            set
            {
                this.measurementTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool measurementTypeSpecified
        {
            get
            {
                return this.measurementTypeFieldSpecified;
            }
            set
            {
                this.measurementTypeFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/lmb/2.1")]
    public enum MeasurementTypeValueType
    {

        /// <remarks/>
        EMISSION,

        /// <remarks/>
        ABSORPTION,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    public partial class LmbAcquisitionPropertyType : AcquisitionPropertyType
    {


        private AcquisitionType acquisitionField;

        [XmlIgnore]
        public LmbAcquisitionType LmbAcquisition
        {
            get
            {
                return (LmbAcquisitionType)this.acquisitionField;
            }
            set
            {
                this.acquisitionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Type=typeof(LmbAcquisitionType), Namespace = "http://www.opengis.net/lmb/2.1")]
        public AcquisitionType Acquisition
        {
            get
            {
                return this.acquisitionField;
            }
            set
            {
                this.acquisitionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AcquisitionType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Acquisition", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbAcquisitionType : AcquisitionType
    {

        private string observationModeField;

        private MeasureType verticalResolutionField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string observationMode
        {
            get
            {
                return this.observationModeField;
            }
            set
            {
                this.observationModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MeasureType verticalResolution
        {
            get
            {
                return this.verticalResolutionField;
            }
            set
            {
                this.verticalResolutionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SensorPropertyType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("SensorPropertyType", Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class LmbSensorPropertyType : SensorPropertyType
    {

        private SensorType sensorField;

        [XmlIgnore]
        public LmbSensorType LmbSensor
        {
            get
            {
                return (LmbSensorType)this.sensorField;
            }
            set
            {
                this.sensorField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Type=typeof(LmbSensorType), Namespace = "http://www.opengis.net/lmb/2.1")]
        public SensorType Acquisition
        {
            get
            {
                return this.sensorField;
            }
            set
            {
                this.sensorField = value;
            }
        }
    }
        

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = true)]
    public partial class LmbFootprintPropertyType : FootprintPropertyType
    {

        [System.Xml.Serialization.XmlElementAttribute(Type=typeof(LmbFootprintType), Namespace = "http://www.opengis.net/lmb/2.1")]
        public override FootprintType Footprint
        {
            get
            {
                return this.footprintField;
            }
            set
            {
                this.footprintField = value;
            }
        }

        [XmlIgnore]
        public LmbFootprintType LmbFootprint
        {
            get
            {
                return (LmbFootprintType)this.footprintField;
            }
            set
            {
                this.footprintField = value;
            }
        }

    }

   
}
