// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.Metadata.EarthObservation.Ogc.Ows</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.Metadata.EarthObservation.W3c.Xlink;


namespace Terradue.Metadata.EarthObservation.Ogc.Ows
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalParametersBaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalParametersType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Metadata", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class MetadataType
    {

        private MetadataTypeAbstractMetaDataAdditionalParameter itemField;

        private typeType typeField;

        private bool typeFieldSpecified;

        private string hrefField;

        private string roleField;

        private string arcroleField;

        private string titleField;

        private showType showField;

        private bool showFieldSpecified;

        private actuateType actuateField;

        private bool actuateFieldSpecified;

        private string aboutField;

        public MetadataType()
        {
            this.typeField = typeType.simple;
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameter", Order = 0)]
        public MetadataTypeAbstractMetaDataAdditionalParameter Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public typeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string arcrole
        {
            get
            {
                return this.arcroleField;
            }
            set
            {
                this.arcroleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public showType show
        {
            get
            {
                return this.showField;
            }
            set
            {
                this.showField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSpecified
        {
            get
            {
                return this.showFieldSpecified;
            }
            set
            {
                this.showFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public actuateType actuate
        {
            get
            {
                return this.actuateField;
            }
            set
            {
                this.actuateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actuateSpecified
        {
            get
            {
                return this.actuateFieldSpecified;
            }
            set
            {
                this.actuateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string about
        {
            get
            {
                return this.aboutField;
            }
            set
            {
                this.aboutField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("AdditionalParameter", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class MetadataTypeAbstractMetaDataAdditionalParameter
    {

        private CodeType nameField;

        private object[] valueField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Value", Order = 1)]
        public object[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NilValueType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Role", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class CodeType
    {

        private string codeSpaceField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string codeSpace
        {
            get
            {
                return this.codeSpaceField;
            }
            set
            {
                this.codeSpaceField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class ContentsBaseType
    {

        private DatasetDescriptionSummaryBaseType[] datasetDescriptionSummaryField;

        private MetadataType[] otherSourceField;

        [System.Xml.Serialization.XmlElementAttribute("DatasetDescriptionSummary", Order = 0)]
        public DatasetDescriptionSummaryBaseType[] DatasetDescriptionSummary
        {
            get
            {
                return this.datasetDescriptionSummaryField;
            }
            set
            {
                this.datasetDescriptionSummaryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("OtherSource", Order = 1)]
        public MetadataType[] OtherSource
        {
            get
            {
                return this.otherSourceField;
            }
            set
            {
                this.otherSourceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("DatasetDescriptionSummary", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class DatasetDescriptionSummaryBaseType : DescriptionType
    {

        private WGS84BoundingBoxType[] wGS84BoundingBoxField;

        private CodeType identifierField;

        private BoundingBoxType[] itemsField;

        private MetadataType[] items1Field;

        private DatasetDescriptionSummaryBaseType[] datasetDescriptionSummaryField;

        [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox", Order = 0)]
        public WGS84BoundingBoxType[] WGS84BoundingBox
        {
            get
            {
                return this.wGS84BoundingBoxField;
            }
            set
            {
                this.wGS84BoundingBoxField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CodeType Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("BoundingBox", typeof(BoundingBoxType), Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox", typeof(WGS84BoundingBoxType), Order = 2)]
        public BoundingBoxType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameters", typeof(AdditionalParametersType), Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("Metadata", typeof(MetadataType), Order = 3)]
        public MetadataType[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DatasetDescriptionSummary", Order = 4)]
        public DatasetDescriptionSummaryBaseType[] DatasetDescriptionSummary
        {
            get
            {
                return this.datasetDescriptionSummaryField;
            }
            set
            {
                this.datasetDescriptionSummaryField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("WGS84BoundingBox", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class WGS84BoundingBoxType : BoundingBoxType
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WGS84BoundingBoxType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("BoundingBox", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class BoundingBoxType
    {

        private string lowerCornerField;

        private string upperCornerField;

        private string crsField;

        private string dimensionsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string LowerCorner
        {
            get
            {
                return this.lowerCornerField;
            }
            set
            {
                this.lowerCornerField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string UpperCorner
        {
            get
            {
                return this.upperCornerField;
            }
            set
            {
                this.upperCornerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string crs
        {
            get
            {
                return this.crsField;
            }
            set
            {
                this.crsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string dimensions
        {
            get
            {
                return this.dimensionsField;
            }
            set
            {
                this.dimensionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("AdditionalParameters", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class AdditionalParametersType : AdditionalParametersBaseType
    {

        private MetadataTypeAbstractMetaDataAdditionalParameter[] additionalParameterField;

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameter", Order = 0)]
        public MetadataTypeAbstractMetaDataAdditionalParameter[] AdditionalParameter
        {
            get
            {
                return this.additionalParameterField;
            }
            set
            {
                this.additionalParameterField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdditionalParametersType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class AdditionalParametersBaseType : MetadataType
    {
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatasetDescriptionSummaryBaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicIdentificationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManifestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceGroupType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class DescriptionType
    {

        private LanguageStringType[] titleField;

        private LanguageStringType[] abstractField;

        private KeywordsType[] keywordsField;

        [System.Xml.Serialization.XmlElementAttribute("Title", Order = 0)]
        public LanguageStringType[] Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Abstract", Order = 1)]
        public LanguageStringType[] Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Keywords", Order = 2)]
        public KeywordsType[] Keywords
        {
            get
            {
                return this.keywordsField;
            }
            set
            {
                this.keywordsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Title", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class LanguageStringType
    {

        private string langField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Keywords", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class KeywordsType
    {

        private LanguageStringType[] keywordField;

        private CodeType typeField;

        [System.Xml.Serialization.XmlElementAttribute("Keyword", Order = 0)]
        public LanguageStringType[] Keyword
        {
            get
            {
                return this.keywordField;
            }
            set
            {
                this.keywordField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CodeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManifestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceGroupType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentificationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class BasicIdentificationType : DescriptionType
    {

        private CodeType identifierField;

        private MetadataType[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameters", typeof(AdditionalParametersType), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Metadata", typeof(MetadataType), Order = 1)]
        public MetadataType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ManifestType : BasicIdentificationType
    {

        private ReferenceGroupType[] referenceGroupField;

        [System.Xml.Serialization.XmlElementAttribute("ReferenceGroup", Order = 0)]
        public ReferenceGroupType[] ReferenceGroup
        {
            get
            {
                return this.referenceGroupField;
            }
            set
            {
                this.referenceGroupField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("ReferenceGroup", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ReferenceGroupType : BasicIdentificationType
    {

        private ReferenceType[] items1Field;

        [System.Xml.Serialization.XmlElementAttribute("Reference", Order = 0)]
        public ReferenceType[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceReferenceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ReferenceType : AbstractReferenceBaseType
    {

        private CodeType identifierField;

        private LanguageStringType[] abstractField;

        private string formatField;

        private MetadataType[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Abstract", Order = 1)]
        public LanguageStringType[] Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameters", typeof(AdditionalParametersType), Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("Metadata", typeof(MetadataType), Order = 3)]
        public MetadataType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceReferenceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("AbstractReferenceBase", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class AbstractReferenceBaseType
    {

        private string typeField;

        private string hrefField;

        private string roleField;

        private string arcroleField;

        private string titleField;

        private showType showField;

        private bool showFieldSpecified;

        private actuateType actuateField;

        private bool actuateFieldSpecified;

        public AbstractReferenceBaseType()
        {
            this.typeField = "simple";
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string arcrole
        {
            get
            {
                return this.arcroleField;
            }
            set
            {
                this.arcroleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public showType show
        {
            get
            {
                return this.showField;
            }
            set
            {
                this.showField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSpecified
        {
            get
            {
                return this.showFieldSpecified;
            }
            set
            {
                this.showFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public actuateType actuate
        {
            get
            {
                return this.actuateField;
            }
            set
            {
                this.actuateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actuateSpecified
        {
            get
            {
                return this.actuateFieldSpecified;
            }
            set
            {
                this.actuateFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("ServiceReference", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ServiceReferenceType : ReferenceType
    {

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("RequestMessage", typeof(object), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RequestMessageReference", typeof(string), DataType = "anyURI", Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class IdentificationType : BasicIdentificationType
    {

        private BoundingBoxType[] items1Field;

        private string[] outputFormatField;

        private string[] items2Field;

        private Items2ChoiceType[] items2ElementNameField;

        [System.Xml.Serialization.XmlElementAttribute("BoundingBox", typeof(BoundingBoxType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox", typeof(WGS84BoundingBoxType), Order = 0)]
        public BoundingBoxType[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("OutputFormat", Order = 1)]
        public string[] OutputFormat
        {
            get
            {
                return this.outputFormatField;
            }
            set
            {
                this.outputFormatField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AvailableCRS", typeof(string), DataType = "anyURI", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute("SupportedCRS", typeof(string), DataType = "anyURI", Order = 2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("Items2ElementName")]
        public string[] Items2
        {
            get
            {
                return this.items2Field;
            }
            set
            {
                this.items2Field = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Items2ElementName", Order = 3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Items2ChoiceType[] Items2ElementName
        {
            get
            {
                return this.items2ElementNameField;
            }
            set
            {
                this.items2ElementNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0", IncludeInSchema = false)]
    public enum Items2ChoiceType
    {

        /// <remarks/>
        AvailableCRS,

        /// <remarks/>
        SupportedCRS,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Exception", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ExceptionType
    {

        private string[] exceptionTextField;

        private string exceptionCodeField;

        private string locatorField;

        [System.Xml.Serialization.XmlElementAttribute("ExceptionText", Order = 0)]
        public string[] ExceptionText
        {
            get
            {
                return this.exceptionTextField;
            }
            set
            {
                this.exceptionTextField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string exceptionCode
        {
            get
            {
                return this.exceptionCodeField;
            }
            set
            {
                this.exceptionCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locator
        {
            get
            {
                return this.locatorField;
            }
            set
            {
                this.locatorField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("GetResourceByID", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class GetResourceByIdType
    {

        private string[] resourceIDField;

        private string outputFormatField;

        private string serviceField;

        private string versionField;

        [System.Xml.Serialization.XmlElementAttribute("ResourceID", DataType = "anyURI", Order = 0)]
        public string[] ResourceID
        {
            get
            {
                return this.resourceIDField;
            }
            set
            {
                this.resourceIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OutputFormat
        {
            get
            {
                return this.outputFormatField;
            }
            set
            {
                this.outputFormatField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("GetCapabilities", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class GetCapabilitiesType
    {

        private string[] acceptVersionsField;

        private string[] sectionsField;

        private string[] acceptFormatsField;

        private string[] acceptLanguagesField;

        private string updateSequenceField;

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Version", IsNullable = false)]
        public string[] AcceptVersions
        {
            get
            {
                return this.acceptVersionsField;
            }
            set
            {
                this.acceptVersionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Section", IsNullable = false)]
        public string[] Sections
        {
            get
            {
                return this.sectionsField;
            }
            set
            {
                this.sectionsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OutputFormat", IsNullable = false)]
        public string[] AcceptFormats
        {
            get
            {
                return this.acceptFormatsField;
            }
            set
            {
                this.acceptFormatsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Language", DataType = "language", IsNullable = false)]
        public string[] AcceptLanguages
        {
            get
            {
                return this.acceptLanguagesField;
            }
            set
            {
                this.acceptLanguagesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updateSequence
        {
            get
            {
                return this.updateSequenceField;
            }
            set
            {
                this.updateSequenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class CapabilitiesBaseType
    {

        private ServiceIdentification serviceIdentificationField;

        private ServiceProvider serviceProviderField;

        private OperationsMetadata operationsMetadataField;

        private string[] languagesField;

        private string versionField;

        private string updateSequenceField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ServiceIdentification ServiceIdentification
        {
            get
            {
                return this.serviceIdentificationField;
            }
            set
            {
                this.serviceIdentificationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ServiceProvider ServiceProvider
        {
            get
            {
                return this.serviceProviderField;
            }
            set
            {
                this.serviceProviderField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public OperationsMetadata OperationsMetadata
        {
            get
            {
                return this.operationsMetadataField;
            }
            set
            {
                this.operationsMetadataField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Language", DataType = "language", IsNullable = false)]
        public string[] Languages
        {
            get
            {
                return this.languagesField;
            }
            set
            {
                this.languagesField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string updateSequence
        {
            get
            {
                return this.updateSequenceField;
            }
            set
            {
                this.updateSequenceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ServiceIdentification : DescriptionType
    {

        private CodeType serviceTypeField;

        private string[] serviceTypeVersionField;

        private string[] profileField;

        private string feesField;

        private string[] accessConstraintsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ServiceTypeVersion", Order = 1)]
        public string[] ServiceTypeVersion
        {
            get
            {
                return this.serviceTypeVersionField;
            }
            set
            {
                this.serviceTypeVersionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Profile", DataType = "anyURI", Order = 2)]
        public string[] Profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Fees
        {
            get
            {
                return this.feesField;
            }
            set
            {
                this.feesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AccessConstraints", Order = 4)]
        public string[] AccessConstraints
        {
            get
            {
                return this.accessConstraintsField;
            }
            set
            {
                this.accessConstraintsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ServiceProvider
    {

        private string providerNameField;

        private OnlineResourceType providerSiteField;

        private ResponsiblePartySubsetType serviceContactField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ProviderName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public OnlineResourceType ProviderSite
        {
            get
            {
                return this.providerSiteField;
            }
            set
            {
                this.providerSiteField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ResponsiblePartySubsetType ServiceContact
        {
            get
            {
                return this.serviceContactField;
            }
            set
            {
                this.serviceContactField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestMethodType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class OnlineResourceType
    {

        private typeType typeField;

        private bool typeFieldSpecified;

        private string hrefField;

        private string roleField;

        private string arcroleField;

        private string titleField;

        private showType showField;

        private bool showFieldSpecified;

        private actuateType actuateField;

        private bool actuateFieldSpecified;

        public OnlineResourceType()
        {
            this.typeField = typeType.simple;
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public typeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
        public string arcrole
        {
            get
            {
                return this.arcroleField;
            }
            set
            {
                this.arcroleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public showType show
        {
            get
            {
                return this.showField;
            }
            set
            {
                this.showField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSpecified
        {
            get
            {
                return this.showFieldSpecified;
            }
            set
            {
                this.showFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
        public actuateType actuate
        {
            get
            {
                return this.actuateField;
            }
            set
            {
                this.actuateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actuateSpecified
        {
            get
            {
                return this.actuateFieldSpecified;
            }
            set
            {
                this.actuateFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class RequestMethodType : OnlineResourceType
    {

        private DomainType[] constraintField;

        [System.Xml.Serialization.XmlElementAttribute("Constraint", Order = 0)]
        public DomainType[] Constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class DomainType : UnNamedDomainType
    {

        private string nameField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DomainType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class UnNamedDomainType
    {

        private object[] allowedValuesField;

        private AnyValue anyValueField;

        private NoValues noValuesField;

        private ValuesReference valuesReferenceField;

        private ValueType defaultValueField;

        private DomainMetadataType meaningField;

        private DomainMetadataType dataTypeField;

        private DomainMetadataType uOMField;

        private DomainMetadataType referenceSystemField;

        private MetadataType[] itemsField;

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Range", typeof(RangeType), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", typeof(ValueType), IsNullable = false)]
        public object[] AllowedValues
        {
            get
            {
                return this.allowedValuesField;
            }
            set
            {
                this.allowedValuesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AnyValue AnyValue
        {
            get
            {
                return this.anyValueField;
            }
            set
            {
                this.anyValueField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public NoValues NoValues
        {
            get
            {
                return this.noValuesField;
            }
            set
            {
                this.noValuesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ValuesReference ValuesReference
        {
            get
            {
                return this.valuesReferenceField;
            }
            set
            {
                this.valuesReferenceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public ValueType DefaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public DomainMetadataType Meaning
        {
            get
            {
                return this.meaningField;
            }
            set
            {
                this.meaningField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public DomainMetadataType DataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public DomainMetadataType UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public DomainMetadataType ReferenceSystem
        {
            get
            {
                return this.referenceSystemField;
            }
            set
            {
                this.referenceSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameters", typeof(AdditionalParametersType), Order = 9)]
        [System.Xml.Serialization.XmlElementAttribute("Metadata", typeof(MetadataType), Order = 9)]
        public MetadataType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Range", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class RangeType
    {

        private ValueType minimumValueField;

        private ValueType maximumValueField;

        private ValueType spacingField;

        private RangeTypeRangeClosure rangeClosureField;

        private bool rangeClosureFieldSpecified;

        public RangeType()
        {
            this.rangeClosureField = RangeTypeRangeClosure.closed;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ValueType MinimumValue
        {
            get
            {
                return this.minimumValueField;
            }
            set
            {
                this.minimumValueField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ValueType MaximumValue
        {
            get
            {
                return this.maximumValueField;
            }
            set
            {
                this.maximumValueField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ValueType Spacing
        {
            get
            {
                return this.spacingField;
            }
            set
            {
                this.spacingField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(RangeTypeRangeClosure.closed)]
        public RangeTypeRangeClosure rangeClosure
        {
            get
            {
                return this.rangeClosureField;
            }
            set
            {
                this.rangeClosureField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rangeClosureSpecified
        {
            get
            {
                return this.rangeClosureFieldSpecified;
            }
            set
            {
                this.rangeClosureFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Value", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ValueType
    {

        private string valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    public enum RangeTypeRangeClosure
    {

        /// <remarks/>
        closed,

        /// <remarks/>
        open,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("open-closed")]
        openclosed,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("closed-open")]
        closedopen,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class AnyValue
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class NoValues
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ValuesReference
    {

        private string referenceField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "anyURI")]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("Meaning", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class DomainMetadataType
    {

        private string referenceField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "anyURI")]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class ResponsiblePartySubsetType
    {

        private string individualNameField;

        private string positionNameField;

        private ContactType contactInfoField;

        private CodeType roleField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IndividualName
        {
            get
            {
                return this.individualNameField;
            }
            set
            {
                this.individualNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string PositionName
        {
            get
            {
                return this.positionNameField;
            }
            set
            {
                this.positionNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ContactType ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CodeType Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("ContactInfo", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ContactType
    {

        private TelephoneType phoneField;

        private AddressType addressField;

        private OnlineResourceType onlineResourceField;

        private string hoursOfServiceField;

        private string contactInstructionsField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TelephoneType Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public OnlineResourceType OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string HoursOfService
        {
            get
            {
                return this.hoursOfServiceField;
            }
            set
            {
                this.hoursOfServiceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ContactInstructions
        {
            get
            {
                return this.contactInstructionsField;
            }
            set
            {
                this.contactInstructionsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class TelephoneType
    {

        private string[] voiceField;

        private string[] facsimileField;

        [System.Xml.Serialization.XmlElementAttribute("Voice", Order = 0)]
        public string[] Voice
        {
            get
            {
                return this.voiceField;
            }
            set
            {
                this.voiceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Facsimile", Order = 1)]
        public string[] Facsimile
        {
            get
            {
                return this.facsimileField;
            }
            set
            {
                this.facsimileField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class AddressType
    {

        private string[] deliveryPointField;

        private string cityField;

        private string administrativeAreaField;

        private string postalCodeField;

        private string countryField;

        private string[] electronicMailAddressField;

        [System.Xml.Serialization.XmlElementAttribute("DeliveryPoint", Order = 0)]
        public string[] DeliveryPoint
        {
            get
            {
                return this.deliveryPointField;
            }
            set
            {
                this.deliveryPointField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string AdministrativeArea
        {
            get
            {
                return this.administrativeAreaField;
            }
            set
            {
                this.administrativeAreaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ElectronicMailAddress", Order = 5)]
        public string[] ElectronicMailAddress
        {
            get
            {
                return this.electronicMailAddressField;
            }
            set
            {
                this.electronicMailAddressField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class OperationsMetadata
    {

        private Operation[] operationField;

        private DomainType[] parameterField;

        private DomainType[] constraintField;

        private object extendedCapabilitiesField;

        [System.Xml.Serialization.XmlElementAttribute("Operation", Order = 0)]
        public Operation[] Operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Parameter", Order = 1)]
        public DomainType[] Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Constraint", Order = 2)]
        public DomainType[] Constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public object ExtendedCapabilities
        {
            get
            {
                return this.extendedCapabilitiesField;
            }
            set
            {
                this.extendedCapabilitiesField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class Operation
    {

        private DCP[] dCPField;

        private DomainType[] parameterField;

        private DomainType[] constraintField;

        private MetadataType[] itemsField;

        private string nameField;

        [System.Xml.Serialization.XmlElementAttribute("DCP", Order = 0)]
        public DCP[] DCP
        {
            get
            {
                return this.dCPField;
            }
            set
            {
                this.dCPField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Parameter", Order = 1)]
        public DomainType[] Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Constraint", Order = 2)]
        public DomainType[] Constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AdditionalParameters", typeof(AdditionalParametersType), Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("Metadata", typeof(MetadataType), Order = 3)]
        public MetadataType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class DCP
    {

        private HTTP itemField;

        [System.Xml.Serialization.XmlElementAttribute("HTTP", Order = 0)]
        public HTTP Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class HTTP
    {

        private RequestMethodType[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        [System.Xml.Serialization.XmlElementAttribute("Get", typeof(RequestMethodType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Post", typeof(RequestMethodType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public RequestMethodType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        Get,

        /// <remarks/>
        Post,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("PointOfContact", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ResponsiblePartyType
    {

        private string individualNameField;

        private string organisationNameField;

        private string positionNameField;

        private ContactType contactInfoField;

        private CodeType roleField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IndividualName
        {
            get
            {
                return this.individualNameField;
            }
            set
            {
                this.individualNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OrganisationName
        {
            get
            {
                return this.organisationNameField;
            }
            set
            {
                this.organisationNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string PositionName
        {
            get
            {
                return this.positionNameField;
            }
            set
            {
                this.positionNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ContactType ContactInfo
        {
            get
            {
                return this.contactInfoField;
            }
            set
            {
                this.contactInfoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CodeType Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute("nilValue", Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class NilValueType : CodeType
    {

        private string nilReasonField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string nilReason
        {
            get
            {
                return this.nilReasonField;
            }
            set
            {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class AllowedValues
    {

        private object[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("Range", typeof(RangeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(ValueType), Order = 0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = false)]
    public partial class ExceptionReport
    {

        private ExceptionType[] exceptionField;

        private string versionField;

        private string langField;

        [System.Xml.Serialization.XmlElementAttribute("Exception", Order = 0)]
        public ExceptionType[] Exception
        {
            get
            {
                return this.exceptionField;
            }
            set
            {
                this.exceptionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class AcceptVersionsType
    {

        private string[] versionField;

        [System.Xml.Serialization.XmlElementAttribute("Version", Order = 0)]
        public string[] Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class SectionsType
    {

        private string[] sectionField;

        [System.Xml.Serialization.XmlElementAttribute("Section", Order = 0)]
        public string[] Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/2.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/2.0", IsNullable = true)]
    public partial class AcceptFormatsType
    {

        private string[] outputFormatField;

        [System.Xml.Serialization.XmlElementAttribute("OutputFormat", Order = 0)]
        public string[] OutputFormat
        {
            get
            {
                return this.outputFormatField;
            }
            set
            {
                this.outputFormatField = value;
            }
        }
    }
}
